### ISSUE TITLE
label formatter

### ISSUE THREAD

**Issue by KivenCkl** [mergeforward/dash_echarts#5]
I want to format the axis label with percentage, but it seems that not support the native js function directly. So what should I do?

yAxis.axisLabel. formatter stringFunction
Formatter of axis label, which supports string template and callback function.

Example:

// Use string template; template variable is the default label of axis {value}
formatter: '{value} kg'
// Use callback.
formatter: function (value, index) {
    return value + 'kg';
}

**Comment by pingf** [comment]
there're several ways to embed simple js func into python code, 
here's one solution:
```python
option = {
...
formatter: 'myformatter'
...
}
dash_echarts.DashECharts( 
            option=option,
            funs={
                "myformatter": '''
                function (value){ 
                    return value + 'kg';
                }
                '''
             },
          fun_values=['myformatter']
)
```

it will replace "myformatter" in option with converted js defined in funs.

**Comment by KivenCkl** [comment]
> there're several ways to embed simple js func into python code,
> here's one solution:
> 
> ```python
> option = {
> ...
> formatter: 'myformatter'
> ...
> }
> dash_echarts.DashECharts( 
>             option=option,
>             funs={
>                 "myformatter": '''
>                 function (value){ 
>                     return value + 'kg';
>                 }
>                 '''
>              },
>           fun_values=['myformatter']
> )
> ```
> 
> it will replace "myformatter" in option with converted js defined in funs.

It works. Thanks a lot.
